name: NuGet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'DotNetCraft.DevTools.DungeonGenerator.sln'
      
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Run Info
      run: |
        echo "The operating system on the runner is $env:RUNNER_OS."
        echo "GITHUB_REF = $env:GITHUB_REF."
        echo "GITHUB_ENV = $env:GITHUB_ENV."
        
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $env:GITHUB_REF
        $version = GetBuildVersion -VersionString $env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x    
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore      

    - name: Run tests
      run: dotnet test --configuration $BUILD_CONFIG --no-restore --no-build --verbosity normal
      
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}