name: NuGet

on:
  tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    
jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'DotNetCraft.DevTools.DungeonGenerator.sln'
      
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:       
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Verify commit exists in origin/master
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/master
    - name: Set BUILD_VERSION variable from tag
      run: echo "BUILD_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
            
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x    
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore      

    - name: Run tests
      run: dotnet test --configuration $BUILD_CONFIG --no-restore --no-build --verbosity normal
      
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}